# Generated by Django 5.2.4 on 2025-08-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='_stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='nombre',
        ),
        migrations.AddField(
            model_name='fecha',
            name='anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='siguiente', to='Inventory.fecha'),
        ),
        migrations.AddField(
            model_name='producto',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='Inventory.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='default_stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='fecha',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='inventario', to='Inventory.fecha'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='InventoryProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='Inventory.inventory')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Inventory.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
