# Generated by Django 5.2.4 on 2025-08-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_remove_inventory__stock_remove_inventory_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
