# Generated by Django 5.2.4 on 2025-08-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_fecha_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fecha',
            name='anterior',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='valor_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='valor_venta',
        ),
        migrations.AddField(
            model_name='inventory',
            name='anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='siguiente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='inventoryproducto',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventarios', to='Inventory.producto'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('fecha', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='factura', to='Inventory.fecha')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas', to='Inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas', to='Inventory.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas', to='Inventory.producto')),
            ],
        ),
    ]
