# Generated by Django 5.2.4 on 2025-08-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_remove_fecha_anterior_remove_producto_valor_compra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryproducto',
            old_name='nombre',
            new_name='producto',
        ),
    ]
