# Generated by Django 5.2.4 on 2025-08-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_rename_nombre_inventoryproducto_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='type',
        ),
        migrations.AlterField(
            model_name='producto',
            name='default_stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FacturasCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compras', to='Inventory.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compras', related_query_name='compras', to='Inventory.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacturasVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventas', to='Inventory.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ventas', related_query_name='ventas', to='Inventory.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Facturas',
        ),
    ]
